version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_gateway:
    build: ./path_to_api_gateway
    ports:
      - "3333:3333"
    depends_on:
      - product_service
      - user_service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=university_db
      - DB_SSL_MODE=disable
      - HTTP_PORT=3333
      - HTTP_TIMEOUT_SECONDS=60

  microservice1:
    build: ./product_service
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

  microservice2:
    build: ./user_service
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

volumes:
  postgres_data:
